[package]
name = "mcp-ox"
version = "0.1.0"
edition = "2024"

[dependencies]
ai-ox = { path = "../ai-ox" }
mcp-sdk = "0.0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
url = "2.5"